module.exports = {
  list: '/api/list',
  addItem: '/api/item/add',
  updateItem: '/api/item/update',
  deleteItem: '/api/item/delete',
  archiveItem: '/api/item/archive',
  searchRecipes: '/api/recipe/search',
  addRecipeItems: '/api/recipe/add',
  archiveAllItems: '/api/item/archiveAll',
  searchRecipes: '/api/recipe/search',
  addRecipeItems: '/api/recipe/add',
  register: '/auth/register',
  login: '/auth/login',
  logout: '/auth/logout',
  token: '/auth/token',
  followUser: '/api/feed/follow',
  getFollowingList: '/api/feed/getFollowing',
  getFollowerItems: '/api/feed/getFollowerItems',
  showArchive: '/api/item/showPast'
};
